[package]
name = "rispc-demo"
version = "0.1.0"
authors = ["Clark Gaebel <cg.wowus.cg@gmail.com>"]
build = "build.rs"

[build-dependencies.rispc]
path = "../rispc"

[dependencies.rispcrt]
path = "../rispcrt"

[dependencies]
time = "0.1"
