language: rust
sudo: true
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.8
    - ubuntu-toolchain-r-test
    packages:
    - libclang-3.8-dev
    - llvm-3.8-dev
rust:
  - stable
  - beta
  - nightly
os:
  - linux
env:
  matrix:
    - LLVM_VERSION=3.8
  global:
    secure: AvI0TpLdhH1TZyxheKfLk3z5TYJhi+0WFOjCcwUYJf2tIQrgJWlEr+SIYISMjYnt/PpQ1CWK+VZMfd7yn2hDdowY3je+UuTo56N9+rHDVuH0RqvB44lp7d9KvwPN+S/vsW4De16B9ZATkRTz0ObuW62DEubfPB1a5ZraeKv7CxRqKNKVt7e9YpTBn8PlGcICdoMbxvYmGkTJ4MAPzCkR5Ic7kYk6TBh017ewSbxuu4902A44qqs6f0xcSDTU+9LToiV9tYkXLk0eBoLRotYayVI8XKLp5tsPi3GmtlR9x9/Tlx5KnbIiSBe8cpxsXMtEqO/9gb71y2Mahf98LtC/VdUzL85uBf8PP4vS3bNejiOizhEQrV8hhWUX3mrGMTt1jCfAq89/l4jvvRGMvUg7tDPiIEFYFyEUSiqvELEzrecAOY1JtwMvbQjn263xpZh2mNlzIg+bSisQgQxA9VtP3sUJ+OcTorhpk1nqURPiI4s55amBBFBtFPanjnlLQwrYK7AJBaZE8stA53TpXpopckNYM3e0kJ9rEYKI2LyXdMTDS6gcN7MQzbosUIZ48Bb632GEASpB3lVh6a6ktO1R3dTWmdEG7kOqp6gI6OJ1Wo5T9TxQ8q9D8psd6z23788o2NHiWGYWVlsiM6/XZ8AVoJFcxkS/2dAmTHXNiAIftoU=

before_script:
  - sudo apt-get install bison git
  - git clone https://github.com/ispc/ispc.git --depth 1 ispc-bin
  - pushd ispc-bin && make -j8 && popd
  - export PATH="$(pwd)/ispc-bin:$PATH"
script:
  - echo "$PATH"
  - pwd
  - pushd rispc-demo && cargo build --release && popd
  - pushd rispc-demo && cargo run   --release && popd
  - pushd rispc && cargo build && popd
  - pushd rispc && cargo test && popd
  - pushd rispc && cargo doc && popd
after_success:
- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=ispc/index.html>' > rispc/target/doc/index.html &&
  git clone --depth 1 https://github.com/davisp/ghp-import &&
  ./ghp-import/ghp-import -n rispc/target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
