[package]
name = "rispcrt"
version = "0.1.0"
authors = ["Clark Gaebel <cg.wowus.cg@gmail.com>"]
build = "build.rs"
description = """
A run-time dependency for packages using the rispc build-time dependency.
"""

[build-dependencies]
gcc = "0.3"
